# 1. Configure environment variables
# GitHub sets default environment variables for every workflow run.
# Replace the variables relative to your project in the "env" section below.
#
# 2. Signing
# Generate a signing certificate in the Windows Application
# Packaging Project or add an existing signing certificate to the project.
# Next, use PowerShell to encode the .pfx file using Base64 encoding
# by running the following Powershell script to generate the output string:
#
# $pfx_cert = Get-Content '.\SigningCertificate.pfx' -Encoding Byte
# [System.Convert]::ToBase64String($pfx_cert) | Out-File 'SigningCertificate_Encoded.txt'
#
# Open the output file, SigningCertificate_Encoded.txt, and copy the
# string inside. Then, add the string to the repo as a GitHub secret
# and name it "Base64_Encoded_Pfx."
# For more information on how to configure your signing certificate for
# this workflow, refer to https://github.com/microsoft/github-actions-for-desktop-apps#signing
#
# Finally, add the signing certificate password to the repo as a secret and name it "Pfx_Key".
# See "Build the Windows Application Packaging project" below to see how the secret is used.

name: .NET Build and Test
on:
  push:
env:
  App_Name: FileRenamerDiff
  App_Directory: src/FileRenamerDiff
  Solution_Directory: src
  Solution_Path: src/FileRenamerDiff.sln
  App_Project_Path: src/FileRenamerDiff/FileRenamerDiff.csproj
  Test_Directory: UnitTests
  Test_Project_Path: src/UnitTests/UnitTests.csproj
  Wap_Project_Directory: FileRenamerDiff_Pack
  Wap_Project_Path: FileRenamerDiff_Pack/FileRenamerDiff_Pack.wapproj
  Signing_Certificate: GitHubActionsWorkflow.pfx
  CodeCov_Result: "lcov.xml"

jobs:
  build:
    strategy:
        matrix:
          configuration: [Release]
    runs-on:
      windows-latest # For a list of available runner types, refer to
      # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    
    steps:
      # Dump for debug workflow
      - name: Dump Github Context
        env:
          GitHub_Context: ${{ toJson(github) }}
        run: echo "${GitHub_Context}"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      # Add  MsBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      # Restore before build and test
      - name: Restore
        run: dotnet restore ${{ env.Solution_Path }}

      - name: Build with dotnet
        run: dotnet build ${{ env.App_Project_Path }} --no-restore
        env:
          Configuration: ${{ matrix.configuration }}

      # Execute all unit tests in the solution
      - name: Execute unit tests
        run: >
          dotnet test ${{ env.Solution_Path }}
          --verbosity normal --no-restore
          --collect:"XPlat Code Coverage"
          /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
          /p:ExcludeByFile="**.Designer.cs%2c**.xaml*%2c**.g.cs%2c**.xaml"
          -p:coverletOutput=${{ env.CodeCov_Result }}
        env:
          Configuration: ${{ matrix.configuration }}

      - name: Send coverage result to codecov
        uses: codecov/codecov-action@v2.0.3
        with:
          files: ${{ env.Solution_Directory }}/${{ env.Test_Directory }}/${{ env.CodeCov_Result }}

  create-release:
    runs-on: windows-latest
    needs: [build]
    if: "contains( github.ref , 'v')"

    steps:
      - name: echos
        shell: bash
        run: |
          echo $RELEASE_VERSION
          echo repo_full=${{ github.repository }}
          echo repo=${{ github.event.repository.name }}
          echo ref_=${{ github.ref }}
          echo sha_=${{ github.sha }}
          echo version=${GITHUB_REF/refs\/tags\/v/}
          echo "repo=${{ github.event.repository.name }}" >> $GITHUB_ENV
          echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
          echo "app_x86_name=${{ env.App_Name }}_app_win-x86_ver${{ env.version }}" >> $GITHUB_ENV
          echo "app_x64_name=${{ env.App_Name }}_app_win-x64_ver${{ env.version }}" >> $GITHUB_ENV
          pwd

      - name: confirm env value
        shell: bash
        run: |
          echo "env.repo=${{ env.repo }}"
          echo "env.version=${{ env.version }}"
          echo "app_x86_name=${{ env.app_x86_name }}"
          echo "app_x64_name=${{ env.app_x64_name }}"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: dotnet publish x86
        run: dotnet publish ${{ env.App_Project_Path }} -c Release -r win-x86 --self-contained true -p:PublishTrimmed=false -p:PublishSingleFile=true -p:PublishReadyToRun=true -o ${{ env.app_x86_name }}
      - name: dotnet publish x64
        run: dotnet publish ${{ env.App_Project_Path }} -c Release -r win-x64 --self-contained true -p:PublishTrimmed=false -p:PublishSingleFile=true -p:PublishReadyToRun=true -o ${{ env.app_x64_name }}

      - name: Copy artifact
        run: |
          mkdir -p outputs
          cp -Literal "${{ env.app_x86_name }}" -Recurse -Destination "outputs\${{ env.app_x86_name }}"
          cp -Literal "${{ env.app_x64_name }}" -Recurse -Destination "outputs\${{ env.app_x64_name }}"
        shell: pwsh

      - name: Archive publish files
        uses: actions/upload-artifact@v1
        with:
          name: FileRenamerDiff_apps
          path: outputs

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: v${{ env.version }}
          release_name: Ver ${{ env.version }}
          body: |
            - Change design
            - Bug fix
          draft: true
          prerelease: false

      - name: Archive packages
        shell: pwsh
        run: |
          Compress-Archive -Path outputs\${{ env.app_x86_name }} -DestinationPath ${{ env.app_x86_name }}.zip
          Compress-Archive -Path outputs\${{ env.app_x64_name }} -DestinationPath ${{ env.app_x64_name }}.zip

      - name: Upload Release Asset
        uses: csexton/release-asset-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_release.outputs.upload_url }}
          files: |
            ${{ env.app_x86_name }}.zip
            ${{ env.app_x64_name }}.zip
    #
    # Decode the base 64 encoded pfx and save the Signing_Certificate
    # - name: Decode the pfx
    #   run: |
    #     $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
    #     $certificatePath = Join-Path -Path $env:Wap_Project_Directory -ChildPath GitHubActionsWorkflow.pfx
    #     [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)
    #
    # Create the app package by building and packaging the Windows Application Packaging project
    # - name: Create the app package
    #   run: msbuild $env:Wap_Project_Path /p:Configuration=$env:Configuration /p:UapAppxPackageBuildMode=$env:Appx_Package_Build_Mode /p:AppxBundle=$env:Appx_Bundle /p:PackageCertificateKeyFile=GitHubActionsWorkflow.pfx /p:PackageCertificatePassword=${{ secrets.Pfx_Key }}
    #   env:
    #     Appx_Bundle: Always
    #     Appx_Bundle_Platforms: x86|x64
    #     Appx_Package_Build_Mode: StoreUpload
    #     Configuration: ${{ matrix.configuration }}
    #
    # Remove the pfx
    # - name: Remove the pfx
    #   run: Remove-Item -path $env:Wap_Project_Directory\$env:Signing_Certificate

#
# Upload the MSIX package: https://github.com/marketplace/actions/upload-artifact
# - name: Upload build artifacts
#   uses: actions/upload-artifact@v2
#   with:
#     name: MSIX Package
#     path: ${{ env.Wap_Project_Directory }}\AppPackages
